### ISSUE TITLE
[AMA]

### ISSUE THREAD

**Issue by kriscgun** [pmarsceill/pmarsceill#10]
#### Ask me anything...

@pmarsceill, 

Hi, I am trying out your really nice jekyll skin just-the-docs for my stats course in the fall and for some reason the relative directory structure is appearing above the H1 header in small font at the top of the page (just below the search box). I can't figure out how to get rid of this and don't see any obvious tags in the YAML config file to toggle this display. It's not appearing on your github.io site for the theme, could you please help me?

thank you,
Kris Gunsalus
NYU

**Comment by pmarsceill** [comment]
1

**Comment by pmarsceill** [comment]
Test

**Comment by pmarsceill** [comment]
Test 2
