### ISSUE TITLE
[AMA]

### ISSUE THREAD

**Issue by gh4n** [pmarsceill/pmarsceill#13]
#### Ask me anything...

@pmarsceill, 
Hey, what happened to tablab.io?

**Comment by pmarsceill** [comment]
Cost too much to run on Heroku at the time... the production DB filled up and I couldn't afford to keep it going. I do think I could rebuild it now for almost nothing. It's very tempting.

**Comment by persuc** [comment]
Plus one to this. Used it to create a couple of tabs and thought it was an awesome tool. If running costs are a problem maybe you could accept donations or else release a client for people to use locally?
