### ISSUE TITLE
[FEEDBACK] Just The Docs

### ISSUE THREAD

**Issue by stungeye** [pmarsceill/pmarsceill#3]
#### Area of feedback

Just The Docs

#### What was your experience?

I just wanted to thank you for creating and maintaining the Just the Docs theme. I'm a college instructor and have used it for all my course. It has worked out so very well. My notes are now so very readable, accessible, navigable, searchable, and maintainable. Hurray!

Thank you kindly for your hard work on this project! 🙏

**Comment by pmarsceill** [comment]
Thank you @stungeye! It's nice to hear that you're finding it useful. I am working on finding time to do a big update to the project in the coming months.
